name: HLS Load Test

on:
  workflow_dispatch:

jobs:
  hls-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull streaming load test image
        run: docker pull unifiedstreaming/streaming-load-testing

      - name: Run HLS load test
        run: |
          docker run --rm \
            -e HOST_URL=https://live1.pulsetv.watch \
            -e MANIFEST_FILE=/hls/stream.m3u8 \
            -e mode=vod \
            -e play_mode=full_playback \
            unifiedstreaming/streaming-load-testing \
            --no-web -c 50 -r 10 --run-time 1m --only-summary
