name: HLS Load Test

on:
  workflow_dispatch:

jobs:
  hls-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t hls-test .

      - name: Run HLS load test
        run: |
          docker run --rm \
            -e HOST_URL=https://live1.pulsetv.watch \
            -e MANIFEST_FILE=/hls/stream.m3u8 \
            -e mode=vod \
            -e play_mode=full_playback \
            unifiedstreaming/streaming-load-testing \
            --no-web -c 10 -r 5 --run-time 60s --only-summary
